### ISSUE TITLE
Redux toolkit

### ISSUE THREAD

**Issue by garrettjoecox** [Th3Wall/Fakeflix#15]
You can cut down quite a bit of your state management boilerplate by using the now recommended [redux toolkit](https://redux-toolkit.js.org/)

**Comment by Th3Wall** [comment]
Hi @garrettjoecox, thanks for the suggestion.

I've chosen the "old" redux on purpose in order to learn the basic version since it's my first React/Redux project. It might help me in the future if I will work on projects built with the older version.
Another important reason about my choice is that when I will use the RTK version I will instantly see and understand the major differences with the older version.

Thanks anyway!
Davide
