### ISSUE TITLE
Registration / Login form is not working 

### ISSUE THREAD

**Issue by kerrybli** [Th3Wall/Fakeflix#26]
I tried to log in with your fake email still I am unable to log in, Even I tried to create a new user by registering still It's not working check out the below ss

![image](https://user-images.githubusercontent.com/43319549/144378975-762e3979-7832-4368-89b7-3b8203ea4907.png)

**Comment by Th3Wall** [comment]
Hi @kerrybli,are you sure to be online while you're trying to do the login?

**Comment by kerrybli** [comment]
Yes, @Th3Wall , My internet connectivity is good, If I am not connected to the internet how can I be able to visit an online site !!

**Comment by Th3Wall** [comment]
Yes, but there are also small disconnections that might occur sometimes...I don't know on what it might depend, I've searched for the error and it seems related to the network, that's why I've asked for it.
BTW, you can still sign in anonymously by clicking on the third CTA "Sign In Anonymously".

Thanks for reporting 😉

**Comment by kerrybli** [comment]
Yes, I did "Sign In Anonymously" too but still it's not working ish
