### ISSUE TITLE
firebase does not have database as based your .env file

### ISSUE THREAD

**Issue by shahishree03** [Th3Wall/Fakeflix#35]
firebase does not have database as based your .env file i.e database of firebase ,but in your src/firebase/firebaseutil.js you have declare firestore .Please check out as firebase auth showing error everytime when sign in and sign up.
Do we have to create database in firebase .Please mention

**Comment by Th3Wall** [comment]
Hey @shahishree03! 😃 
I don't know if I understood what you're saying but basically, in order to have the project working, you need to create a project on Firebase and you need to extract the configuration params and set them inside the .env file.

Let me know if you're still encountering issues and I'll try to help you 😄 

Th3Wall
